// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkUjNQeNbbl0dHq1pawT51ne-IRsR_hc',
    appId: '1:933588607579:web:a8840e5674c474291ed57e',
    messagingSenderId: '933588607579',
    projectId: 'task-focus-4i2ic',
    authDomain: 'task-focus-4i2ic.firebaseapp.com',
    storageBucket: 'task-focus-4i2ic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_fg5JiYj-Z8cQyqleBWXPQz-zF1UXrI',
    appId: '1:933588607579:android:0f425a1728704f5d1ed57e',
    messagingSenderId: '933588607579',
    projectId: 'task-focus-4i2ic',
    storageBucket: 'task-focus-4i2ic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_k6UsznF0j5AFRcnZA_AxQILYfh_BrY',
    appId: '1:933588607579:ios:a4a0e83cf9127c941ed57e',
    messagingSenderId: '933588607579',
    projectId: 'task-focus-4i2ic',
    storageBucket: 'task-focus-4i2ic.firebasestorage.app',
    iosClientId: '933588607579-dv6ikta1usng3s6eimmjf7bfsdmaf320.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataTransmit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_k6UsznF0j5AFRcnZA_AxQILYfh_BrY',
    appId: '1:933588607579:ios:a4a0e83cf9127c941ed57e',
    messagingSenderId: '933588607579',
    projectId: 'task-focus-4i2ic',
    storageBucket: 'task-focus-4i2ic.firebasestorage.app',
    iosClientId: '933588607579-dv6ikta1usng3s6eimmjf7bfsdmaf320.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataTransmit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLkUjNQeNbbl0dHq1pawT51ne-IRsR_hc',
    appId: '1:933588607579:web:a8840e5674c474291ed57e',
    messagingSenderId: '933588607579',
    projectId: 'task-focus-4i2ic',
    authDomain: 'task-focus-4i2ic.firebaseapp.com',
    storageBucket: 'task-focus-4i2ic.firebasestorage.app',
  );
}
